//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQMailMerge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInformation
    {
        public int Id { get; set; }
        public string LetterFrom { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string SenderDesignation { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    }
}
